#!/bin/bash 

RED="\033[1;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"

if [ $1 = --help ]
then
	 echo search \(フォルダ名\) \(正規表現\)
	 exit 0
fi

echo $1/
echo
if [ $1 ]; then
	LS=$(ls $1)
	for ele in ${LS// /}
	do
		if test -d $1/$ele; then
			:
		else
			if [[ $ele =~ c$|__ ]]; then
				:
			else
				ff=$(cat < $1/$ele | grep -nE $2) #https://dev.classmethod.jp/tool/character-code-and-line-feed-code-converting-tools-matome/
				if [[ -n $ff ]]; then
					echo
					echo -e ${RED}$ele
					#echo "$ff"
					lines=$(echo "$ff")
					while read line #https://qiita.com/todanano/items/312693668f5c4615147d
					do
						[[ $line =~ ^([0-9]+):(.*)($2)(.*)$ ]]
						echo -ne ${YELLOW}"${BASH_REMATCH[1]}"${BLUE}:${WHITE}${BASH_REMATCH[2]}${CYAN}${BASH_REMATCH[3]}${WHITE}${BASH_REMATCH[4]}"\n"
					done << END
					$lines
END
				fi
			fi
		fi
	done
else
	echo "input folda name"
fi
